language: rust
dist: xenial
cache: cargo
sudo: required

rust:
  - nightly

env:
  matrix:
    - FEATURES=""
    - FEATURES="--features nom-verbose-errors"
    - FEATURES="--no-default-features"
    - FEATURES="--no-default-features --features quoted-string-rfc2047"

addons:
  apt:
    packages:
      # For codecov
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

cache:
  directories:
    - /home/travis/.cargo

before_cache:
  - rm -rf /home/travis/.cargo/registry

script:
  - eval cargo build --verbose $FEATURES
  - eval cargo test --verbose $FEATURES

# Coverage report
after_success:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" && "$FEATURES" == "" ]]; then
        wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
        tar xzf master.tar.gz &&
        cd kcov-master &&
        mkdir build &&
        cd build &&
        cmake .. &&
        make &&
        sudo make install &&
        cd ../.. &&
        rm -rf kcov-master &&
        (GLOBIGNORE='*.d'; for file in target/debug/rustyknife-*; do mkdir -p "target/cov/$(basename $file)"; kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done) &&
        bash <(curl -s https://codecov.io/bash) &&
        echo "Uploaded code coverage"
      fi
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" && "$FEATURES" == "" ]]; then
          cargo doc &&
          echo "<meta http-equiv=refresh content=0;url=$)echo \"$TRAVIS_REPO_SLUG\" | cut -d '/' -f 2)/index.html>" > target/doc/index.html &&
          sudo pip install ghp-import &&
          ghp-import -n target/doc &&
          git push -fq "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" gh-pages
      fi
