language: rust
dist: xenial
cache: cargo

rust:
  - nightly

env:
  matrix:
    - FEATURES=""
    - FEATURES="--features nom-verbose-errors"
    - FEATURES="--no-default-features"
    - FEATURES="--no-default-features --features quoted-string-rfc2047"

cache:
  directories:
    - /home/travis/.cargo

before_cache:
  - rm -rf /home/travis/.cargo/registry

script:
  - eval cargo build --verbose $FEATURES
  - eval cargo test --verbose $FEATURES
