[package]
name = "rustyknife"
version = "0.1.4"
authors = ["Jonathan Bastien-Filiatrault <jonathan@zerospam.ca>"]
edition = "2018"

[features]
default = ["quoted-string-rfc2047", "python"]
quoted-string-rfc2047 = []
nom-verbose-errors = ["nom/verbose-errors"]
python = ["memmap", "pyo3"]

[lib]
name = "rustyknife"
crate-type = ["cdylib", "rlib"]

[dependencies]
encoding = "0.2.33"
nom = "^4.2"
base64 = "0.10.1"

memmap = { version = "0.7.0", optional=true }
pyo3 = { version = "0.6.0-alpha.4", features = ["extension-module"], optional=true }

[profile.release]
panic = "abort"
