[package]
name = "rustyknife"
version = "0.1.0"
authors = ["Jonathan Bastien-Filiatrault <jonathan@zerospam.ca>"]

[lib]
name = "rustyknife"
crate-type = ["cdylib", "rlib"]

[dependencies]
encoding = "0.2"

[dependencies.nom]
git = "https://github.com/Geal/nom"
tag = "4.0.0-beta2"
features = ["verbose-errors"]

[dependencies.pyo3]
git = "https://github.com/PyO3/pyo3"
branch = "master"
features = ["python3", "extension-module"]
