[package]
name = "rustyknife"
version = "0.1.4"
authors = ["Jonathan Bastien-Filiatrault <jonathan@zerospam.ca>"]
edition = "2018"

[features]
default = ["quoted-string-rfc2047"]
quoted-string-rfc2047 = []
nom-verbose-errors = ["nom/verbose-errors"]

[lib]
name = "rustyknife"
crate-type = ["cdylib", "rlib"]

[dependencies]
encoding = "0.2.33"
memmap = "0.7.0"
base64 = "0.10.1"

[dependencies.nom]
version = "4.0.0"

[dependencies.pyo3]
version = "=0.6.0-alpha.2"
features = ["extension-module"]

[profile.release]
panic = "abort"
