[package]
name = "rustyknife"
version = "0.1.0"
authors = ["Jonathan Bastien-Filiatrault <jonathan@zerospam.ca>"]

[lib]
name = "rustyknife"
crate-type = ["cdylib", "rlib"]

[dependencies]
encoding = "0.2"
memmap = "0.6.2"

[dependencies.nom]
git = "https://github.com/zerospam/nom"
branch = "fixwarning"
features = ["verbose-errors"]

[dependencies.pyo3]
git = "https://github.com/PyO3/pyo3"
branch = "master"
features = ["python3", "extension-module"]

[profile.release]
panic = "abort"
