[package]
name = "rustyknife"
version = "0.1.4"
authors = ["Jonathan Bastien-Filiatrault <jonathan@zerospam.ca>"]
edition = "2018"

[features]
default = ["quoted-string-rfc2047"]
quoted-string-rfc2047 = []
nom-verbose-errors = ["nom/verbose-errors"]

[lib]
name = "rustyknife"
crate-type = ["cdylib", "rlib"]

[dependencies]
encoding = "0.2"
memmap = "0.6.2"
base64 = "~0.6.0"

[dependencies.nom]
version = "4.0.0"

[dependencies.pyo3]
version = "0.2.7"
features = ["python3", "extension-module"]

[profile.release]
panic = "abort"
