[package]
name = "rustyknife"
version = "0.1.0"
authors = ["Jonathan Bastien-Filiatrault <jonathan@zerospam.ca>"]

[dependencies.nom]
git = "https://github.com/Geal/nom"
tag = "4.0.0-beta2"
features = ["verbose-errors"]
